// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleGax

/// Unified Maintenance service
///
/// @Snippet(path: "MaintenanceQuickstart")
public final class MaintenanceClient: Clients.MaintenanceProtocol, Sendable {
  let inner: any Clients.MaintenanceStub

  /// Creates a new `MaintenanceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.MaintenanceStub = try Clients.MaintenanceTransport(options)
    inner = Clients.MaintenanceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.MaintenanceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Retrieves the statistics of a specific maintenance.
  ///
  /// @Snippet(path: "Maintenance_SummarizeMaintenances")
  public func summarizeMaintenances(
    request: SummarizeMaintenancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMaintenanceApiV1.SummarizeMaintenancesResponse {
    try await self.inner.summarizeMaintenances(request: request, options: options)
  }

  /// Retrieve a collection of resource maintenances.
  ///
  /// @Snippet(path: "Maintenance_ListResourceMaintenances")
  public func listResourceMaintenances(
    request: ListResourceMaintenancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMaintenanceApiV1.ListResourceMaintenancesResponse {
    try await self.inner.listResourceMaintenances(request: request, options: options)
  }

  /// Retrieve a single resource maintenance.
  ///
  /// @Snippet(path: "Maintenance_GetResourceMaintenance")
  public func getResourceMaintenance(
    request: GetResourceMaintenanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMaintenanceApiV1.ResourceMaintenance {
    try await self.inner.getResourceMaintenance(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Maintenance_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "Maintenance_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `MaintenanceClient`.
  ///
  /// To mock `MaintenanceClient` change your functions to receive
  /// `some MaintenanceProtocol` or `any MaintenanceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol MaintenanceProtocol: Sendable {
    /// See `MaintenanceClient.summarizeMaintenances`.
    func summarizeMaintenances(
      request: SummarizeMaintenancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMaintenanceApiV1.SummarizeMaintenancesResponse

    /// See `MaintenanceClient.listResourceMaintenances`.
    func listResourceMaintenances(
      request: ListResourceMaintenancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMaintenanceApiV1.ListResourceMaintenancesResponse

    /// See `MaintenanceClient.getResourceMaintenance`.
    func getResourceMaintenance(
      request: GetResourceMaintenanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudMaintenanceApiV1.ResourceMaintenance

    /// See `MaintenanceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `MaintenanceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}

// Default implementations
extension Clients.MaintenanceProtocol {
  public func summarizeMaintenances(request: SummarizeMaintenancesRequest) async throws
    -> GoogleCloudMaintenanceApiV1.SummarizeMaintenancesResponse
  {
    try await self.summarizeMaintenances(request: request, options: .init())
  }

  public func summarizeMaintenances(
    request: SummarizeMaintenancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMaintenanceApiV1.SummarizeMaintenancesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func summarizeMaintenancesByItems(
    request: SummarizeMaintenancesRequest
  ) -> any AsyncSequence<MaintenanceSummary, Swift.Error> {
    self.summarizeMaintenancesByItems(request: request, options: .init())
  }

  /// Retrieves the statistics of a specific maintenance.
  ///
  /// @Snippet(path: "Maintenance_SummarizeMaintenances")
  public func summarizeMaintenancesByItems(
    request: SummarizeMaintenancesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<MaintenanceSummary, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudMaintenanceApiV1.SummarizeMaintenancesResponse in
      var request = request
      request.pageToken = token
      return try await self.summarizeMaintenances(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func summarizeMaintenancesByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<MaintenanceSummary, Swift.Error> {
    let request = SummarizeMaintenancesRequest().with {
      $0.parent = parent
    }
    return self.summarizeMaintenancesByItems(request: request)
  }

  public func listResourceMaintenances(request: ListResourceMaintenancesRequest) async throws
    -> GoogleCloudMaintenanceApiV1.ListResourceMaintenancesResponse
  {
    try await self.listResourceMaintenances(request: request, options: .init())
  }

  public func listResourceMaintenances(
    request: ListResourceMaintenancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMaintenanceApiV1.ListResourceMaintenancesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listResourceMaintenancesByItems(
    request: ListResourceMaintenancesRequest
  ) -> any AsyncSequence<ResourceMaintenance, Swift.Error> {
    self.listResourceMaintenancesByItems(request: request, options: .init())
  }

  /// Retrieve a collection of resource maintenances.
  ///
  /// @Snippet(path: "Maintenance_ListResourceMaintenances")
  public func listResourceMaintenancesByItems(
    request: ListResourceMaintenancesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<ResourceMaintenance, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudMaintenanceApiV1.ListResourceMaintenancesResponse in
      var request = request
      request.pageToken = token
      return try await self.listResourceMaintenances(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listResourceMaintenancesByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<ResourceMaintenance, Swift.Error> {
    let request = ListResourceMaintenancesRequest().with {
      $0.parent = parent
    }
    return self.listResourceMaintenancesByItems(request: request)
  }

  public func getResourceMaintenance(request: GetResourceMaintenanceRequest) async throws
    -> GoogleCloudMaintenanceApiV1.ResourceMaintenance
  {
    try await self.getResourceMaintenance(request: request, options: .init())
  }

  public func getResourceMaintenance(
    request: GetResourceMaintenanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudMaintenanceApiV1.ResourceMaintenance {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getResourceMaintenance(
    name: Swift.String,
  ) async throws -> GoogleCloudMaintenanceApiV1.ResourceMaintenance {
    let request = GetResourceMaintenanceRequest().with {
      $0.name = name
    }
    return try await self.getResourceMaintenance(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Maintenance_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }
}
