// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// MaintenanceSummary contains maintenance statistics calculated based on
/// ResourceMaintenances within the scope: project and location.
public struct MaintenanceSummary: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The name of the maintenance.
  public var maintenanceName: Swift.String = Swift.String()

  /// Output only. The title of the maintenance.
  public var title: Swift.String = Swift.String()

  /// Output only. The description of the maintenance.
  public var description: Swift.String = Swift.String()

  /// Output only. The category of the maintenance event.
  public var category: MaintenanceCategory = MaintenanceCategory()

  /// Output only. Scheduled start time of the maintenance. The maintenance will
  /// start at `maintenanceScheduledStartTime` or later, with best effort to
  /// finish before `maintenanceScheduledEndTime`.
  public var maintenanceScheduledStartTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. An estimated (best effort, not guaranteed) end time of the
  /// scheduled maintenance.
  public var maintenanceScheduledEndTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Actual date when the maintenance started. Field present only
  /// after the state changed to `RUNNING`.
  public var maintenanceStartTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Actual date when the maintenance successfully completed. Field
  /// present only after the state changed to `SUCCEEDED`.
  public var maintenanceEndTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Indicates whether the user has some control over that
  /// maintenance, either proactively before maintenance was scheduled with
  /// maintenance policy or with reactive controls after it was scheduled (see
  /// controls field).
  public var userControllable: Swift.Bool = Swift.Bool()

  /// Output only. Control available for that Maintenance (might not be available
  /// for every resource that maintenance is applied to).
  public var controls: [MaintenanceControl] = []

  /// Output only. Stats is a field of ResourceMaintenance used to aggregate the
  /// stats.
  public var stats: [MaintenanceSummary.Stats] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MaintenanceSummary`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MaintenanceSummary().with { $0.maintenanceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let maintenanceName = CodingKeys(stringValue: "maintenanceName")
    static let title = CodingKeys(stringValue: "title")
    static let description = CodingKeys(stringValue: "description")
    static let category = CodingKeys(stringValue: "category")
    static let maintenanceScheduledStartTime = CodingKeys(
      stringValue: "maintenanceScheduledStartTime")
    static let maintenanceScheduledEndTime = CodingKeys(stringValue: "maintenanceScheduledEndTime")
    static let maintenanceStartTime = CodingKeys(stringValue: "maintenanceStartTime")
    static let maintenanceEndTime = CodingKeys(stringValue: "maintenanceEndTime")
    static let userControllable = CodingKeys(stringValue: "userControllable")
    static let controls = CodingKeys(stringValue: "controls")
    static let stats = CodingKeys(stringValue: "stats")

    static let _knownKeys: Set<Swift.String> = [
      "maintenanceName",
      "title",
      "description",
      "category",
      "maintenanceScheduledStartTime",
      "maintenanceScheduledEndTime",
      "maintenanceStartTime",
      "maintenanceEndTime",
      "userControllable",
      "controls",
      "stats",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .maintenanceName) {
      self.maintenanceName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .title) {
      self.title = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(MaintenanceCategory.self, forKey: .category) {
      self.category = value
    }
    self.maintenanceScheduledStartTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .maintenanceScheduledStartTime)
    self.maintenanceScheduledEndTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .maintenanceScheduledEndTime)
    self.maintenanceStartTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .maintenanceStartTime)
    self.maintenanceEndTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .maintenanceEndTime)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .userControllable) {
      self.userControllable = value
    }
    if let value = try container.decodeIfPresent([MaintenanceControl].self, forKey: .controls) {
      self.controls = value
    }
    if let value = try container.decodeIfPresent([MaintenanceSummary.Stats].self, forKey: .stats) {
      self.stats = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.maintenanceName, forKey: .maintenanceName)
    try container.encode(self.title, forKey: .title)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.category, forKey: .category)
    try container.encodeIfPresent(
      self.maintenanceScheduledStartTime, forKey: .maintenanceScheduledStartTime)
    try container.encodeIfPresent(
      self.maintenanceScheduledEndTime, forKey: .maintenanceScheduledEndTime)
    try container.encodeIfPresent(self.maintenanceStartTime, forKey: .maintenanceStartTime)
    try container.encodeIfPresent(self.maintenanceEndTime, forKey: .maintenanceEndTime)
    try container.encode(self.userControllable, forKey: .userControllable)
    try container.encode(self.controls, forKey: .controls)
    try container.encode(self.stats, forKey: .stats)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Stats indicates the type of aggregate and the corresponding aggregates.
  public struct Stats: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// groupBy specifies the type of aggregate.
    /// For example a group_by might be `"state"`
    public var groupBy: Swift.String = Swift.String()

    /// Aggregates is a list <group, count> pairs. For example, if the
    /// group_by is `"state"` a possible tuple in the aggregates list could be
    /// "SCHEDULED" : `11`,
    public var aggregates: [MaintenanceSummary.Aggregate] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Stats`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Stats().with { $0.groupBy = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let groupBy = CodingKeys(stringValue: "groupBy")
      static let aggregates = CodingKeys(stringValue: "aggregates")

      static let _knownKeys: Set<Swift.String> = [
        "groupBy",
        "aggregates",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .groupBy) {
        self.groupBy = value
      }
      if let value = try container.decodeIfPresent(
        [MaintenanceSummary.Aggregate].self, forKey: .aggregates)
      {
        self.aggregates = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.groupBy, forKey: .groupBy)
      try container.encode(self.aggregates, forKey: .aggregates)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.maintenance.api.v1.MaintenanceSummary.Stats"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Aggregate is a <group, count> pair.
  public struct Aggregate: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Specifies what specific value of the group_by the count represents. For
    /// example if group_by is `"state"` its corresponding group could be
    /// `"SCHEDULED"`.
    public var group: Swift.String = Swift.String()

    /// The count of the group.
    public var count: Swift.Int64 = Swift.Int64()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Aggregate`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Aggregate().with { $0.group = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let group = CodingKeys(stringValue: "group")
      static let count = CodingKeys(stringValue: "count")

      static let _knownKeys: Set<Swift.String> = [
        "group",
        "count",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .group) {
        self.group = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .count) {
        self.count = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.group, forKey: .group)
      try container.encode(self.count, forKey: .count)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.maintenance.api.v1.MaintenanceSummary.Aggregate"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.maintenance.api.v1.MaintenanceSummary"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
