// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ResourceMaintenance is a resource that represents a maintenance operation
/// on a resource.
public struct ResourceMaintenance: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the resource_maintenance resource.
  /// Format:
  /// `"projects/{project}/locations/{location}/resourceMaintenance/{resource-maintenance-id}"`
  public var name: Swift.String = Swift.String()

  /// Output only. The resource spec of the resource maintenance.
  public var resource: ResourceMaintenance.Resource? = nil

  /// Output only. The details of the maintenance.
  public var maintenance: ResourceMaintenance.Maintenance? = nil

  /// Output only. The state of the resource maintenance.
  public var state: ResourceMaintenance.State = ResourceMaintenance.State()

  /// Output only. The create time of the resource maintenance.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The update time of the resource maintenance.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time when the resource maintenance has started.
  public var maintenanceStartTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time when the resource maintenance has completed.
  public var maintenanceEndTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time when the resource maintenance was cancelled.
  public var maintenanceCancelTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time when the maintenance on the resource was scheduled to
  /// start.
  public var maintenanceScheduledStartTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time when the maintenance on the resource was scheduled to
  /// end.
  public var maintenanceScheduledEndTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Indicates whether the user has some control over that
  /// maintenance, either proactively before maintenance was scheduled with
  /// maintenance policy or with reactive controls after it was scheduled (see
  /// controls field)
  public var userControllable: Swift.Bool = Swift.Bool()

  /// Output only. The controls of the maintenance.
  public var controls: [MaintenanceControl] = []

  /// Optional. The labels on the resource, which can be used for categorization.
  /// similar to Kubernetes resource labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Annotations is an unstructured key-value map stored with a
  /// resource that may be set by external tools to store and retrieve arbitrary
  /// metadata. They are not queryable and should be preserved when modifying
  /// objects.
  ///
  /// More info: https://kubernetes.io/docs/user-guide/annotations
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. The unique identifier of the resource. UID is unique in the
  /// time and space for this resource within the scope of the service. It is
  /// typically generated by the server on successful creation of a resource
  /// and must not be changed. UID is used to uniquely identify resources
  /// with resource name reuses. This should be a UUID4.
  public var uid: Swift.String = Swift.String()

  /// Output only. An opaque value that uniquely identifies a version or
  /// generation of a resource. It can be used to confirm that the client
  /// and server agree on the ordering of a resource being written.
  public var etag: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ResourceMaintenance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceMaintenance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let resource = CodingKeys(stringValue: "resource")
    static let maintenance = CodingKeys(stringValue: "maintenance")
    static let state = CodingKeys(stringValue: "state")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let maintenanceStartTime = CodingKeys(stringValue: "maintenanceStartTime")
    static let maintenanceEndTime = CodingKeys(stringValue: "maintenanceEndTime")
    static let maintenanceCancelTime = CodingKeys(stringValue: "maintenanceCancelTime")
    static let maintenanceScheduledStartTime = CodingKeys(
      stringValue: "maintenanceScheduledStartTime")
    static let maintenanceScheduledEndTime = CodingKeys(stringValue: "maintenanceScheduledEndTime")
    static let userControllable = CodingKeys(stringValue: "userControllable")
    static let controls = CodingKeys(stringValue: "controls")
    static let labels = CodingKeys(stringValue: "labels")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let uid = CodingKeys(stringValue: "uid")
    static let etag = CodingKeys(stringValue: "etag")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "resource",
      "maintenance",
      "state",
      "createTime",
      "updateTime",
      "maintenanceStartTime",
      "maintenanceEndTime",
      "maintenanceCancelTime",
      "maintenanceScheduledStartTime",
      "maintenanceScheduledEndTime",
      "userControllable",
      "controls",
      "labels",
      "annotations",
      "uid",
      "etag",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.resource = try container.decodeIfPresent(
      ResourceMaintenance.Resource.self, forKey: .resource)
    self.maintenance = try container.decodeIfPresent(
      ResourceMaintenance.Maintenance.self, forKey: .maintenance)
    if let value = try container.decodeIfPresent(ResourceMaintenance.State.self, forKey: .state) {
      self.state = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    self.maintenanceStartTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .maintenanceStartTime)
    self.maintenanceEndTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .maintenanceEndTime)
    self.maintenanceCancelTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .maintenanceCancelTime)
    self.maintenanceScheduledStartTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .maintenanceScheduledStartTime)
    self.maintenanceScheduledEndTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .maintenanceScheduledEndTime)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .userControllable) {
      self.userControllable = value
    }
    if let value = try container.decodeIfPresent([MaintenanceControl].self, forKey: .controls) {
      self.controls = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.resource, forKey: .resource)
    try container.encodeIfPresent(self.maintenance, forKey: .maintenance)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.maintenanceStartTime, forKey: .maintenanceStartTime)
    try container.encodeIfPresent(self.maintenanceEndTime, forKey: .maintenanceEndTime)
    try container.encodeIfPresent(self.maintenanceCancelTime, forKey: .maintenanceCancelTime)
    try container.encodeIfPresent(
      self.maintenanceScheduledStartTime, forKey: .maintenanceScheduledStartTime)
    try container.encodeIfPresent(
      self.maintenanceScheduledEndTime, forKey: .maintenanceScheduledEndTime)
    try container.encode(self.userControllable, forKey: .userControllable)
    try container.encode(self.controls, forKey: .controls)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.etag, forKey: .etag)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Resource contains information about the resource affected by maintenance.
  public struct Resource: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. Name is the reference to the consumer resource affected by
    /// the maintenance. Available values can be found here:
    /// https://cloud.google.com/asset-inventory/docs/asset-names
    public var resourceName: Swift.String = Swift.String()

    /// Output only. The location of the resource.
    /// Format:
    /// `us-central1`
    public var location: Swift.String = Swift.String()

    /// Output only. The type of the resource.
    /// Available values can be found here:
    /// https://cloud.google.com/asset-inventory/docs/asset-types#supported_resource_types
    /// Please note that not all the resource types will have their maintenances
    /// reported.
    public var type: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Resource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Resource().with { $0.resourceName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let resourceName = CodingKeys(stringValue: "resourceName")
      static let location = CodingKeys(stringValue: "location")
      static let type = CodingKeys(stringValue: "type")

      static let _knownKeys: Set<Swift.String> = [
        "resourceName",
        "location",
        "type",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceName) {
        self.resourceName = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .location) {
        self.location = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
        self.type = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.resourceName, forKey: .resourceName)
      try container.encode(self.location, forKey: .location)
      try container.encode(self.type, forKey: .type)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.maintenance.api.v1.ResourceMaintenance.Resource"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Maintenance is the maintenance details of a resource's maintenance.
  public struct Maintenance: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Maintenance is the name of the corresponding maintenance resource
    /// following the standard naming scheme: `"{maintenance-id}"`
    public var maintenanceName: Swift.String = Swift.String()

    /// Output only. The title of the maintenance.
    public var title: Swift.String = Swift.String()

    /// Output only. The description of the maintenance.
    public var description: Swift.String = Swift.String()

    /// Output only. The category of the maintenance.
    public var category: MaintenanceCategory = MaintenanceCategory()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Maintenance`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Maintenance().with { $0.maintenanceName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let maintenanceName = CodingKeys(stringValue: "maintenanceName")
      static let title = CodingKeys(stringValue: "title")
      static let description = CodingKeys(stringValue: "description")
      static let category = CodingKeys(stringValue: "category")

      static let _knownKeys: Set<Swift.String> = [
        "maintenanceName",
        "title",
        "description",
        "category",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .maintenanceName) {
        self.maintenanceName = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .title) {
        self.title = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
        self.description = value
      }
      if let value = try container.decodeIfPresent(MaintenanceCategory.self, forKey: .category) {
        self.category = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.maintenanceName, forKey: .maintenanceName)
      try container.encode(self.title, forKey: .title)
      try container.encode(self.description, forKey: .description)
      try container.encode(self.category, forKey: .category)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.maintenance.api.v1.ResourceMaintenance.Maintenance"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// State is the state of a resource maintenance.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state.
    case unspecified
    /// Scheduled for a particular window. For disruptive maintenance it should
    /// respect maintenance policy, i.e. its available windows, exclusions and
    /// notification period.
    case scheduled
    /// Maintenance is ongoing.
    case running
    /// No longer planned, typically when other maintenance (e.g. upgrade to
    /// newer version) already happened, or the user skipped the maintenance.
    case cancelled
    /// Successfully completed.
    case succeeded
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .scheduled: return 1
      case .running: return 2
      case .cancelled: return 3
      case .succeeded: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .scheduled: return "SCHEDULED"
      case .running: return "RUNNING"
      case .cancelled: return "CANCELLED"
      case .succeeded: return "SUCCEEDED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "SCHEDULED": self = .scheduled
      case "RUNNING": self = .running
      case "CANCELLED": self = .cancelled
      case "SUCCEEDED": self = .succeeded
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .scheduled
      case 2: self = .running
      case 3: self = .cancelled
      case 4: self = .succeeded
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .scheduled: return try container.encode("SCHEDULED")
      case .running: return try container.encode("RUNNING")
      case .cancelled: return try container.encode("CANCELLED")
      case .succeeded: return try container.encode("SUCCEEDED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.maintenance.api.v1.ResourceMaintenance"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
